# Generated by Django 2.2.1 on 2019-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190607_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name_plural': 'BookCopies'},
        ),
        migrations.AddField(
            model_name='book',
            name='total_rating',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='book',
            name='total_users',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
