# Generated by Django 2.2.1 on 2019-06-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190614_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
    ]
