# Generated by Django 2.2.1 on 2019-06-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190615_0330'),
        ('store', '0007_auto_20190609_2005'),
    ]

    operations = [
    ]
