# Generated by Django 2.2.1 on 2019-06-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_20190616_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating_total',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating_users',
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_users',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='borrow_date',
            field=models.DateField(null=True),
        ),
    ]
